### ISSUE TITLE
Add extension foundation

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/PersistentPageIdentifiers#1]
Best done by @malberts or @JeroenDeDauw 

AC
* Correct ASCII art in the commit message :)
* MediaWiki extension shows up on Special:Version
* i18n present
* Optional (can be follow up): our latest local CI setup (PHPUnit, PHPCS, PHPStan)
* Optional (can be follow up): our latest GH Actions config
* ???

**Comment by malberts** [comment]
Added in https://github.com/ProfessionalWiki/PersistentPageIdentifiers/commit/0ca3a477cc4ccc02f151cec22ab77b1def57e3a8

Includes all of the AC.

![Image](https://github.com/user-attachments/assets/07b770e1-e06b-4c31-a42a-57a1b6fef29b)
