### ISSUE TITLE
Run CI with MySQL and SQLite

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/PersistentPageIdentifiers#24]
From https://github.com/ProfessionalWiki/PersistentPageIdentifiers/pull/20#discussion_r1838980679

All jobs don't necessarily have to run on both. Figure out an acceptible spread.

**Comment by waximabbax** [comment]
I am planning to work on this in the next 4-20 hours but I don't wanna cookie-lick it. So I'll assign it to myself when I start, before that feel free to work on this if its important to you.
