### ISSUE TITLE
Create parser function stub

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/PersistentPageIdentifiers#6]
AC:
* [ ] parser function name: TODO
* [ ] has no arguments
* [ ] can just print Hello World

**Comment by malberts** [comment]
Needs a bit of name bikeshedding.
``{{PAGEID}}`` already exists in core, so we need to somehow distinguish the "persistent" part.
The most explicit would be: `{{#persistent_page_id}}`.
And the shortest, would be: `{{#ppid}}`. This one is the least obvious from the name itself, but might be nicer to use for the admins who know what it's for.

**Comment by kghbln** [comment]
Waht aboout `{{#ppageid}}`. Anyhow, the shorter, the better.
