### ISSUE TITLE
Create service for getting pages without persistent ID

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/PersistentPageIdentifiers#7]
To be used by the maintenance script: https://github.com/ProfessionalWiki/PersistentPageIdentifiers/issues/5

AC:
* [ ] Return only pages without the ID. depends on https://github.com/ProfessionalWiki/PersistentPageIdentifiers/issues/8

**Comment by JeroenDeDauw** [comment]
Probably best implemented with something Iterator-like. 

I did a brief look for such code we wrote in the best. Found two cases which are both basic but perhaps exactly what we need:
* EntitySource and implementations in https://github.com/ProfessionalWiki/WikibaseExport
* EntitySource and ItemSource in https://github.com/ProfessionalWiki/GND/tree/master/src/Adapters/DataAccess 

I'm not finding anything that deals with plain MediaWiki pages or matches our "all pages matching condition" use case.

**Comment by malberts** [comment]
I suspect the implementation can be much simpler since it's only going to be used by the maintenance script. We don't need to iterate over Page objects that need to be retrieved first. We just need the page IDs exactly as they are retrieved from a SQL query, and then pass that to the persistent ID creator service.
